
name: AI Auto Fix

on:
  workflow_dispatch:
    inputs:
      jiraKey:
        description: "Jira issue key"
        required: true
      summary:
        description: "Issue summary"
        required: true
      description:
        description: "Issue description / stack trace"
        required: true

jobs:
  ai-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Fetch Java class from public repo
        run: |
          RAW_URL="https://raw.githubusercontent.com/dinukrana2000/Rest_Api_Bloging_Web/develop_AI_Testing/src/main/java/com/exmple/dinuk/service/Impl/PostServiceImpl.java"
          curl -s $RAW_URL -o PostServiceImpl.txt
          echo "Saved PostServiceImpl.java to PostServiceImpl.txt"

      - name: Call OpenAI to generate patch
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          PROMPT=$(cat <<EOF
          Jira Issue: ${{ github.event.inputs.jiraKey }}
          Summary: ${{ github.event.inputs.summary }}
          Description: ${{ github.event.inputs.description }}

          Here is the full code of the affected file (PostServiceImpl.java):
          $(<PostServiceImpl.txt)

          Suggest a git diff patch to fix the issue. 
          Return only valid unified git diff format, starting with 'diff --git'.
          Do not wrap with triple backticks or explanations.
          EOF
          )

          JSON_BODY=$(jq -n --arg role "user" --arg content "$PROMPT" \
           '{model:"gpt-4o-mini", messages:[{role:"system", content:"You are an expert Java developer. Always return only a valid raw unified git diff patch. The diff must start with 'diff --git'. Do not wrap output in triple backticks or explanations. If a line should be removed, use '-' only. If a line should be added, use '+' only. Do not comment out lines as a 'fix'. Ensure the hunk headers (@@ -X,Y +X,Y @@) correctly match the file context."}, {role:$role, content:$content}]}')

          RESPONSE=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d "$JSON_BODY")

          echo "$RESPONSE" | jq -r '.choices[0].message.content' > AI_PATCH.diff

          # Remove accidental markdown fences
          sed -i '/^```/d' AI_PATCH.diff

          # Ensure patch starts with proper header
          FILE_PATH="src/main/java/com/exmple/dinuk/service/Impl/PostServiceImpl.java"
          if ! grep -q "^diff --git" AI_PATCH.diff; then
            echo "⚠️ AI forgot diff header, fixing..."
            TMP=$(mktemp)
            echo "diff --git a/$FILE_PATH b/$FILE_PATH" > "$TMP"
            echo "index 0000000..1111111 100644" >> "$TMP"
            cat AI_PATCH.diff >> "$TMP"
            mv "$TMP" AI_PATCH.diff
          fi

          echo "---- FINAL PATCH ----"
          cat AI_PATCH.diff

      - name: Apply AI Patch
        run: |
          if [ -s AI_PATCH.diff ]; then
            echo "Applying AI suggested patch..."
            if git apply AI_PATCH.diff; then
              echo "✅ Patch applied successfully"
            else
              echo "❌ Patch failed, please review AI_PATCH.diff manually."
              exit 1
            fi
          else
            echo "No patch generated by AI."
            exit 1
          fi

      - name: Commit AI Fix
        run: |
          BRANCH="ai-fix-${{ github.event.inputs.jiraKey }}"
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git checkout -b "$BRANCH"
          git add src/main/java/com/exmple/dinuk/service/Impl/PostServiceImpl.java
          git commit -m "AI fix suggestion for ${{ github.event.inputs.jiraKey }}"
          git push origin "$BRANCH"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ai-fix-${{ github.event.inputs.jiraKey }}
          title: "AI Fix for ${{ github.event.inputs.jiraKey }}"
          base: develop_AI_Testing
          body: |
            This PR contains an AI-suggested fix.

            Jira Key: ${{ github.event.inputs.jiraKey }}
            Summary: ${{ github.event.inputs.summary }}
            Description: ${{ github.event.inputs.description }}
