name: AI Auto Fix

on:
  workflow_dispatch:
    inputs:
      jiraKey:
        description: "Jira issue key"
        required: true
      summary:
        description: "Issue summary"
        required: true
      description:
        description: "Issue description / stack trace"
        required: true

jobs:
  ai-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Fetch Java class from public repo
        run: |
          RAW_URL="https://raw.githubusercontent.com/dinukrana2000/Rest_Api_Bloging_Web/develop_AI_Testing/src/main/java/com/exmple/dinuk/service/Impl/PostServiceImpl.java"
          curl -s $RAW_URL -o PostServiceImpl.java
          echo "Saved PostServiceImpl.java to PostServiceImpl.txt"

      - name: Call OpenAI to generate patch
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          FILE_CONTENT=$(<PostServiceImpl.txt)

          PROMPT="Jira Issue: ${{ github.event.inputs.jiraKey }}
          Summary: ${{ github.event.inputs.summary }}
          Description: ${{ github.event.inputs.description }}

          Here is the full code of the affected file (PostServiceImpl.java):
          $FILE_CONTENT

          Suggest a git diff patch to fix the issue. Return only valid unified diff format, no explanations."

          RESPONSE=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d '{
              "model": "gpt-4o-mini",
              "messages": [
                {"role": "system", "content": "You are an expert Java developer. Return only a valid unified git diff patch."},
                {"role": "user", "content": "'"$PROMPT"'"}
              ]
            }')

          echo "$RESPONSE" | jq -r '.choices[0].message.content' > AI_PATCH.diff
          echo "AI Patch generated:"
          cat AI_PATCH.diff || echo "No patch generated by AI"

      - name: Apply AI Patch
        run: |
          if [ -s AI_PATCH.diff ]; then
            echo "Applying AI suggested patch..."
            git apply AI_PATCH.diff || echo "Patch failed, please review AI_PATCH.diff manually."
          else
            echo "No patch generated by AI."
            exit 1
          fi

      - name: Commit AI Fix
        run: |
          BRANCH="ai-fix-${{ github.event.inputs.jiraKey }}"
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git checkout -b "$BRANCH"
          git add .
          git commit -m "AI fix suggestion for ${{ github.event.inputs.jiraKey }}"
          git push origin "$BRANCH"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ai-fix-${{ github.event.inputs.jiraKey }}
          title: "AI Fix for ${{ github.event.inputs.jiraKey }}"
          base: develop_AI_Testing
          body: |
            This PR contains an AI-suggested fix.

            Jira Key: ${{ github.event.inputs.jiraKey }}
            Summary: ${{ github.event.inputs.summary }}
            Description: ${{ github.event.inputs.description }}
