name: AI Auto Fix

on:
  workflow_dispatch:
    inputs:
      jiraKey:
        description: "Jira issue key"
        required: true
      summary:
        description: "Issue summary"
        required: true
      description:
        description: "Issue description"
        required: true

jobs:
  ai-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      # Step 1: Identify affected classes
      - name: Identify affected classes
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Identifying affected classes from error..."
          PROMPT="Jira Issue: ${{ github.event.inputs.jiraKey }}
          Summary: ${{ github.event.inputs.summary }}
          Description: ${{ github.event.inputs.description }}

          Given this error/stack trace, list the fully qualified Java classes or file paths in this repo likely responsible. Return only file paths relative to repo, no explanations."

          RESPONSE=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d '{
              "model": "gpt-4o-mini",
              "messages": [
                {"role": "system", "content": "You are an expert Java developer. Return only file paths or class names."},
                {"role": "user", "content": "'"$PROMPT"'"}
              ]
            }')

          echo "$RESPONSE" | jq -r '.choices[0].message.content' > affected_classes.txt
          echo "Affected classes/files:"
          cat affected_classes.txt

      # Step 2: Generate AI patch
      - name: Generate AI Patch
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          FILES_CONTENT=""
          for f in $(cat affected_classes.txt); do
            FILES_CONTENT="$FILES_CONTENT\n\n$f:\n$(cat $f)"
          done

          PROMPT="Jira Issue: ${{ github.event.inputs.jiraKey }}
          Summary: ${{ github.event.inputs.summary }}
          Description: ${{ github.event.inputs.description }}

          Here is the code of affected files:
          $FILES_CONTENT

          Suggest a git diff patch to fix the issue. Return only valid unified diff format, no explanations."

          RESPONSE=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d '{
              "model": "gpt-4o-mini",
              "messages": [
                {"role": "system", "content": "You are an expert developer. Return only a valid unified git diff patch."},
                {"role": "user", "content": "'"$PROMPT"'"}
              ]
            }')

          echo "$RESPONSE" | jq -r '.choices[0].message.content' > AI_PATCH.diff
          echo "AI Patch generated:"
          cat AI_PATCH.diff

      # Step 3: Apply AI Patch
      - name: Apply AI Patch
        run: |
          if [ -s AI_PATCH.diff ]; then
            echo "Applying AI suggested patch..."
            git apply AI_PATCH.diff || echo "Patch failed, please review AI_PATCH.diff manually."
          else
            echo "No patch generated by AI."
            exit 1
          fi

      # Step 4: Commit AI Fix
      - name: Commit AI Fix
        run: |
          BRANCH="ai-fix-${{ github.event.inputs.jiraKey }}"
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git checkout -b "$BRANCH"
          git add .
          git commit -m "AI fix suggestion for ${{ github.event.inputs.jiraKey }}"
          git push origin "$BRANCH"

      # Step 5: Create Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ai-fix-${{ github.event.inputs.jiraKey }}
          base: develop_AI_Testing
          title: "AI Fix for ${{ github.event.inputs.jiraKey }}"
          body: |
            This PR contains an AI-suggested fix.

            Jira Key: ${{ github.event.inputs.jiraKey }}
            Summary: ${{ github.event.inputs.summary }}
            Description: ${{ github.event.inputs.description }}
